# Reference: https://github.com/SeleniumHQ/docker-selenium

# If you want to give a default test and then keep container alive (not needed anymore with our new approach to do this)
# command: sh -c "mvn clean test -Dhost=grid -DaccessGridFrom=container -Dbrowser=chrome -Dmaven.test.failure.ignore=true
#     && tail -f /dev/null"

# To run this compose file: docker compose up
# Then to run the tests: docker container exec -it drona_test mvn clean test
version: '3.9'
services:
  test:
    build: .
    container_name: drona_test
    volumes:
      - .:/usr/src
      - /dev/shm:/dev/shm
    working_dir: '/usr/src'
    deploy:
      replicas: 1
    command: sh -c "echo 'ready to test' && tail -f /dev/null"